# Generated by Django 4.2.6 on 2023-12-02 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20, null=True)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('date_upload', models.DateField(auto_now_add=True)),
                ('date_download', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.TextField()),
                ('file_size', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_cloud_app.user')),
            ],
        ),
    ]
