# Generated by Django 4.2.6 on 2023-12-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cloud_app', '0005_file_link_for_download_alter_file_date_download_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
